/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface MyD3 {
        "data": string;
        "height": number;
        "width": number;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyD3Element extends Components.MyD3, HTMLStencilElement {
    }
    var HTMLMyD3Element: {
        prototype: HTMLMyD3Element;
        new (): HTMLMyD3Element;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "my-d3": HTMLMyD3Element;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
        "onSelect"?: (event: CustomEvent<any>) => void;
    }
    interface MyD3 {
        "data"?: string;
        "height"?: number;
        "onExportImage"?: (event: CustomEvent<any>) => void;
        "width"?: number;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "my-d3": MyD3;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-d3": LocalJSX.MyD3 & JSXBase.HTMLAttributes<HTMLMyD3Element>;
        }
    }
}
